# Generated by Django 3.0.8 on 2020-07-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
