# Generated by Django 3.0.8 on 2020-08-09 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '__first__'),
        ('usercards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuizzesProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_datetime', models.DateTimeField(auto_now=True)),
                ('correct_answers', models.FloatField()),
                ('passed', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quizzes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quizzes')),
            ],
        ),
    ]
