# Generated by Django 3.0.8 on 2020-07-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercards', '0002_auto_20200718_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='birthday',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
