# Generated by Django 3.0.8 on 2020-08-10 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/quizzes/%d-%m-%YT%H.%M.%S.%f/')),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('published_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('person', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/questions/%d-%m-%YT%H.%M.%S.%f/')),
                ('content', models.TextField()),
                ('quizzes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quizzes')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('published_datetime', models.DateTimeField(auto_now=True)),
                ('allowed', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('quizzes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quizzes')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/answers/%d-%m-%YT%H.%M.%S.%f/')),
                ('content', models.TextField()),
                ('correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Question')),
            ],
        ),
    ]
