# Generated by Django 3.0.8 on 2020-08-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
