# Generated by Django 3.0.8 on 2020-08-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20200811_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='image',
            new_name='photo',
        ),
    ]
