# Generated by Django 3.0.8 on 2020-08-14 06:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20200813_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/quizzes/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/quizzes/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/quizzes/'), upload_to=''),
        ),
    ]
