# Generated by Django 3.0.8 on 2020-08-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20200814_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='is_publ',
            field=models.BooleanField(default=False),
        ),
    ]
