# Generated by Django 3.0.8 on 2020-08-14 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0008_auto_20200814_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='q_person',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='q_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
